config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :departures
    end
  end
  resources :departures
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "departures#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departure.rb
class Departure < ApplicationRecord
end

app/controllers/api/v1/departures_controller.rb
class Api::V1::DeparturesController < ApplicationController
  def index
    @departures = Departure.where(confirmed: false).or(Departure.where(confirmed: true).where('confirmed_time > ?', Time.current - 5.minutes))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  before_action :set_departure, only: %i[ show edit update destroy ]

  # GET /departures or /departures.json
  def index
    @departures = Departure.where(confirmed: false).or(Departure.where(confirmed: true).where('confirmed_time > ?', Time.current - 5.minutes))
  end

  # GET /departures/1 or /departures/1.json
  def show
  end

  # GET /departures/new
  def new
    @departure = Departure.new
  end

  # GET /departures/1/edit
  def edit
  end

  # POST /departures or /departures.json
  def create
    @departure = Departure.new(departure_params)
    if @departure.loaded
      @departure.loaded_time = Time.current
    end

    respond_to do |format|
      if @departure.save
        format.html { redirect_to departures_url, notice: "Departure was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departures/1 or /departures/1.json
  def update
    need_to_save = false

    if @departure.loaded && params[:departure][:loaded] == '0'
      # the user has changed the record to not loaded
      @departure.loaded_time = ''
      @departure.confirmed = false
      @departure.confirmed_time = ''
      params[:confirmed] = ''
      need_to_save = true
    elsif params[:departure][:loaded] == '1' && !@departure.loaded
      # the user has changed the record to loaded
      @departure.loaded_time = Time.current
      need_to_save = true
    end

    if params[:departure][:confirmed] == '1' && !@departure.confirmed
      @departure.confirmed_time = Time.current
      need_to_save = true
    elsif params[:departure][:confirmed] == '0'
      # confirmed turned off
      @departure.confirmed_time = ''
      need_to_save = true
    end

    if need_to_save
      @departure.save
    end

    respond_to do |format|
      if @departure.update(departure_params)
        format.html { redirect_to departures_url, notice: "Departure was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departures/1 or /departures/1.json
  def destroy
    @departure.destroy

    respond_to do |format|
      format.html { redirect_to departures_url, notice: "Departure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departure
      @departure = Departure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departure_params
      params.require(:departure).permit(:door, :truck, :route, :loader, :driver, :loaded, :confirmed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_date(date)
    if date
      formatted = date.strftime("%H:%M:%S")
    else
      formatted = ' '
    end
  end
end

app/helpers/departures_helper.rb
module DeparturesHelper
end

app/views/departures/_form.html.erb
<%= form_with(model: departure) do |form| %>
  <% if departure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departure.errors.count, "error") %> prohibited this departure from being saved:</h2>

      <ul>
        <% departure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :door %> </th>
        <th> <%= form.label :truck %> </th>
        <th> <%= form.label :route %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.text_field :door %> </td>
        <td> <%= form.text_field :truck %> </td>
        <td> <%= form.text_field :route %> </td>
      </tr>
    </tbody>
  </table>

  <table>
    <thead>
      <tr>
        <th> <%= form.label :loader %> </th>
        <th> <%= form.label :loaded %> </th>
        <th> <%= form.label :driver %> </th>
        <th> <%= form.label :confirmed %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.text_field :loader %> </td>
        <td> <%= form.check_box :loaded %> </td>
        <td> <%= form.text_field :driver %> </td>
        <% if @departure.loaded %>
          <td> <%= form.check_box :confirmed %> </td>
        <% else %>
          <td style="display:none;"> <%= form.check_box :confirmed %> </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departures/edit.html.erb
<h2>Edit</h2>

<%= render "form", departure: @departure %>

app/views/departures/index.html.erb
<br>
<br>
<br>
<p style="color: green"><%= notice %></p>

<div ng-app="departuresApp" ng-controller="indexCtrl">
  <table>
    <thead>
      <tr>
        <th>Door</th>
        <th>Truck</th>
        <th>Route</th>
        <th>Loader</th>
        <th>Loaded</th>
        <th>Driver</th>
        <th>Departed</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
        <tr ng-repeat="departure in departures">
          <td>{{departure.door}} </td>
          <td>{{departure.truck}} </td>
          <td>{{departure.route}} </td>
          <td>{{departure.loader}} </td>
          <td>{{departure.loaded_time}} </td>
          <td>{{departure.driver}} </td>
          <td>{{departure.confirmed_time}} </td>
          <td><a href="http://localhost:3000/departures/{{departure.id}}/edit" class="btn btn-primary">Edit</a></td>
        </tr>
    </tbody>
  </table>
  <script src="/assets/indexCtrl.js"></script>
</div>

app/views/departures/new.html.erb
<h2>New departure</h2>

<%= render "form", departure: @departure %>

app/views/layouts/_header.html.erb
<span class="primary-logo">
</span>
<h1 class="title">Departures</h1>

<div id="navbar">
  <span><%= link_to 'List', departures_path, class: "btn btn-primary" %></span>
  <span><%= link_to 'New Departure', new_departure_path, class: "btn btn-primary" %></span>
</div>
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Departures</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="global">
        <div style="position: fixed; top: 0px; width: 100%; height: 4em; background-color: white; z-index: 100;">
          <%= render 'layouts/header' %>
        </div>
        <div style="margin-top: 4.5em;">
          <%= yield %>
        </div>
      </div>
  </body>
</html>